language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - if [ "${COMPILER}" == "clang" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
  - if [ "${COMPILER}" == "clang" ]; then sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${COMPILER_VERSION} main' >> /etc/apt/sources.list"; fi
  - sudo apt-get update -qq

install:
  - if [ "${COMPILER}" == "g++" ]; then sudo apt-get install -qq g++-${COMPILER_VERSION} && export CC=gcc-${COMPILER_VERSION} CXX=g++-${COMPILER_VERSION}; fi
  - if [ "${COMPILER}" == "clang" ]; then sudo apt-get install --allow-unauthenticated -qq clang-${COMPILER_VERSION} libc++-dev libc++-abi-dev && export CC=clang-${COMPILER_VERSION} CXX=clang++-${COMPILER_VERSION} CXXFLAGS="${CXXFLAGS} -stdlib=libc++ -lc++abi"; fi
  - if [ "$USE_CMAKE" = "TRUE" ]; then sudo apt-get install -qq cmake; fi

  - sudo apt-get install -y libmpg123-dev libsndfile-dev libsdl2-dev
  - sudo pip install cpp-coveralls

# Ubuntu 12.04 doesn't have a libuv package, so we install it from source.
before_script:
  - ./make_libuv.sh

script:
  - if [ "$USE_CMAKE" = "FALSE" ]; then ./config.sh && make coverage; fi
  - if [ "$USE_CMAKE" = "TRUE" ]; then mkdir cbuild && cd cbuild; cmake .. && make && make check; fi

# coveralls doesn't like gcc (segfaults)
after_success:
  - if [ "$CXX" == "clang++-3.8" ] && [ "$USE_CMAKE" == "FALSE" ]; then coveralls -b . --exclude src/tests --exclude src/contrib --gcov="`which llvm-cov-3.8`" --gcov-options="gcov"; fi

matrix:
  include:
    - compiler: clang
      env: COMPILER=clang COMPILER_VERSION=3.7 USE_CMAKE=TRUE
    - compiler: clang
      env: COMPILER=clang COMPILER_VERSION=3.8 USE_CMAKE=TRUE
    - compiler: clang
      env: COMPILER=clang COMPILER_VERSION=3.8 USE_CMAKE=FALSE
