language: cpp

dist: bionic
addons:
  apt:
    packages:
      - libmpg123-dev
      - libsndfile-dev
      - libsdl2-dev
      - libuv1-dev
      # The pack-in libstdc++ in Bionic doesn't support C++17, weirdly.
      - libstdc++-8-dev
      # These packages aren't actually needed on all builds, but it's easier to
      # specify them up here than have to specify apt packages again and again for
      # each matrix section that needs extra packages.
      - gcc-8
      - g++-8

# We'd just use 'compiler' here, but we have to specify GCC8,
# which requires some environment fun.
matrix:
  include:
    # standard Bionic clang ('just works' with libstdc++-8)
    - os: linux
      compiler: clang
    # gcc 8 (at time of writing, Bionic gcc won't work for weird C++17 reasons)
    - os: linux
      compiler: gcc
      env:
        - CC="gcc-8"
        - CXX="g++-8"

before_script:
  - mkdir cbuild && cd cbuild
  - cmake ..

script:
  - make
  - make check
  - cpack

deploy:
  provider: releases
  api_key:
    secure: D9oITRuGGGqA23zx1SUin5mPv8G9bmQ7CBAI2VpnmlOlCqUWdxD099l1DBe2q+5WBEV4hZcahHDHHQyiZcDtDs/swrjSgnJ7WVfc/dJJczJo/8JKa1qJ8SKwgt1Lh0voCh9eZj4NE+spTqj6xZ2KdHOFWZgclx8zMEqNE2LNF/6pPzz+5QsjpiZYTk84bhjDAafJoFn3/Bk6Q5lBrzoUdkIsHQvQuTYk4cOSpprtYqBRq/IoDeDBI/EfmjEDUi9Iw8xCEA2Il2MFmWDxXZXmxEzoqwt/lt2aBc9CiS77N7hAz8o4/u4rsS9fF4bQeTItdoJnm5X8fP7st3BFcE6yQOjshUw31YpnzpOsKh8CQfSdxGUXem3MTNw0ja+ayXsiqerCX/mZ2v29v6vBQJy2GHbA4imbLqIqmENaMutHaPAOCAMmWNWwh2w3HeDn7LHbELHqSaFCYF3E0GuReG2Y5puzEtv2RnX1y8m0dJVQgjeZ2KLD8uGt2rEIklOcJ14HvEh8Shhijnt/q0aO35JqkBQ6vA8mrD9gOYUe4PYcIal38v0KwHKW5zjvcyQQhJETvw6pOM4wNW9MP45Z5YL8v2w5n/N/jGmZeAXh0b09by2UBht4ZIbX6ShZKWG5cDt1JEKbCHMJtwnRvDzhPGaATVblVriJuE2jVcRenM/QCaQ=
  file_glob: true
  file: "*.deb"
  skip_cleanup: true
  draft: true
  on:
    tags: true
    branch: travis-deb
