language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - if [ "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
  - if [ "$CXX" == "clang++" ]; then sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"; fi 
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.5; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi

  - sudo apt-get install -y libsox-dev portaudio19-dev
  - sudo pip install cpp-coveralls

# Ubuntu 12.04 doesn't have a libuv package, so we install it from source.
before_script:
  - ./make_libuv.sh

compiler:
  - clang
  - gcc

script:
  - ./config.sh && make coverage

# coveralls doesn't like gcc (segfaults)
after_success:
  - if [ "$CXX" == "clang++-3.5" ]; then coveralls -b . --exclude src/tests --exclude src/contrib --gcov="`which llvm-cov-3.5`"; fi

notifications:
  irc:
    channels:
      - "chat.freenode.net#ury"
    template:
      - "%{repository_name} %{branch} %{result} | %{build_url} | %{commit} by %{author}: %{commit_message}"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
