language: cpp

# Ubuntu 12.04 doesn't have a libuv package, so we install it from source.
before_script:
  - wget https://github.com/joyent/libuv/archive/v0.11.29.tar.gz -O /tmp/libuv.tar.gz
  - pushd
  - cd /tmp
  - tar xzf libuv.tar.gz
  - cd libuv-0.11.29
  - sh autogen.sh
  - ./configure
  - make
  - make check
  - sudo make install
  - popd

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsox-dev portaudio19-dev

compiler:
  - clang
  - gcc

script: make

