#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

platform:
  - x64
  - x86

configuration: Release

install:
  # show all available env vars
  - set
  - echo cmake on AppVeyor
  - cmake -version
  - ps: >-
      If ($env:PLATFORM -Match "x64") {
        $env:PYTHON="C:\Python27-x64\python.exe"
      } Else {
        $env:PYTHON="C:\Python27\python.exe"
      }
  - python --version
  - ps: .\WindowsBuilder.ps1 -deps -arch "$env:PLATFORM"

build_script:
  - cd c:\projects\ury-playd
  - ps: .\WindowsBuilder.ps1 -playd -arch "$env:PLATFORM"

test_script:
  - cd C:\projects\ury-playd\%PLATFORM%\build
  - ctest --output-on-failure
    -C "%CONFIGURATION%"

after_build:
  - cd C:\projects\ury-playd
  - 7z a playd_%PLATFORM%.zip C:\projects\ury-playd\%PLATFORM%\build\Release\playd.exe

artifacts:
  - path: playd_$(PLATFORM).zip
    name: playd $(PLATFORM)

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: g+7eD+rmWu28F2F7iswR5HtuLA39wnUajHLhMfhF/tXskWi/EtdERORXmrWZwZkh
  artifact: playd_$(PLATFORM).zip
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true