#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

# Operating system (build VM template)
os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  - x64
  - x86

configuration: Release

environment:
  project: C:\projects\ury-playd

install:
  # show all available env vars
  - set
  - echo cmake on AppVeyor
  - cmake -version
  - ps: >-
      If ($env:PLATFORM -Match "x64") {
        $env:PYTHON="C:\Python27-x64\python.exe"
        $env:PlatformString="win64"
      } Else {
        $env:PYTHON="C:\Python27\python.exe"
        $env:PlatformString="win32"
      }
  - python --version
  - ps: .\WindowsBuilder.ps1 -deps -arch "$env:PLATFORM" -sh "C:\cygwin\bin\bash.exe"

build_script:
  - cd "%project%"
  - ps: .\WindowsBuilder.ps1 -playd -arch "$env:PLATFORM"

test_script:
  - cd "%project%\%PLATFORM%\build"
  - ctest --output-on-failure
    -C "%CONFIGURATION%"

after_build:
  - set zipname="playd_%APPVEYOR_REPO_TAG_NAME%_%PlatformString%.zip"
  - set zippath="%project%\%zipname%"
  - 7z a "%zippath%" LICENSE*
  - cd "%project%\%PLATFORM%\build\%CONFIGURATION%"
  - 7z a "%zippath%" *

artifacts:
  - path: playd_$(APPVEYOR_REPO_TAG_NAME)_$(PlatformString).zip
    name: playd $(APPVEYOR_REPO_TAG_NAME) $(PlatformString)

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: g+7eD+rmWu28F2F7iswR5HtuLA39wnUajHLhMfhF/tXskWi/EtdERORXmrWZwZkh
  artifact: playd_$(APPVEYOR_REPO_TAG_NAME)_$(PlatformString).zip
  draft: true
  prerelease: true
  force_update: false
  on:
    appveyor_repo_tag: true
